# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Publish to JSR

on:
  release:
    types: [created]
  workflow_dispatch:
   inputs:
      npm_version:
        description: 'Version number to publish on JSR X.Y.Z'
        required: true
permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: v1.43.3

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          
      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

      - name: git status
        # run: npx jsr publish
        run: git status
      # deno.lock make build dirty so we need to allow dirty

      - name: Publish package ${{inputs.npm_version}}
        run: deno publish --allow-dirty
